CREATE TABLE BUCKET (
    ID CHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CREATED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL,
    ALLOW_BUNDLE_OVERWRITE BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX BUCKET_NAME_IDX ON BUCKET (NAME);

CREATE TABLE FLOW (
    ID CHAR(36) NOT NULL,
    BUCKET_ID CHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX FLOW_BUCKET_ID_NAME_IDX ON FLOW (BUCKET_ID, NAME);

CREATE TABLE FLOW_SNAPSHOT (
    FLOW_ID CHAR(36) NOT NULL,
    VERSION INTEGER NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    JSON_BODY TEXT NOT NULL,
    COMMENTS VARCHAR(1024),
    BUCKET_ID CHAR(36) NOT NULL,
    FLOW_NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY (FLOW_ID, VERSION)
);

CREATE INDEX FLOW_SNAPSHOT_FLOW_ID_IDX ON FLOW_SNAPSHOT (FLOW_ID);
CREATE INDEX FLOW_SNAPSHOT_BUCKET_ID_IDX ON FLOW_SNAPSHOT (BUCKET_ID);
CREATE INDEX FLOW_SNAPSHOT_FLOW_NAME_IDX ON FLOW_SNAPSHOT (FLOW_NAME);

CREATE TABLE EXTENSION_BUNDLE (
    ID CHAR(36) NOT NULL,
    BUCKET_ID CHAR(36) NOT NULL,
    GROUP_ID VARCHAR(256) NOT NULL,
    ARTIFACT_ID VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX EXT_BUNDLE_BUCKET_GROUP_ARTIFACT_IDX ON EXTENSION_BUNDLE (BUCKET_ID, GROUP_ID, ARTIFACT_ID);

CREATE TABLE EXTENSION_BUNDLE_VERSION (
    ID CHAR(36) NOT NULL,
    BUNDLE_ID CHAR(36) NOT NULL,
    VERSION VARCHAR(256) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(1024),
    BUILD_INFO_JSON TEXT,
    FILE_SIZE INTEGER NOT NULL,
    SHA_256 VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX EXT_BUNDLE_VERSION_BUNDLE_ID_VERSION_IDX ON EXTENSION_BUNDLE_VERSION (BUNDLE_ID, VERSION);
CREATE INDEX EXT_BUNDLE_VERSION_BUNDLE_ID_IDX ON EXTENSION_BUNDLE_VERSION (BUNDLE_ID);

CREATE TABLE EXTENSION_BUNDLE_VERSION_DEPENDENCY (
    BUNDLE_VERSION_ID CHAR(36) NOT NULL,
    GROUP_ID VARCHAR(256) NOT NULL,
    ARTIFACT_ID VARCHAR(256) NOT NULL,
    VERSION VARCHAR(256) NOT NULL
);

CREATE INDEX EXT_BUNDLE_VERSION_DEPENDENCY_BUNDLE_VERSION_ID_IDX ON EXTENSION_BUNDLE_VERSION_DEPENDENCY (BUNDLE_VERSION_ID);

