apiVersion: registry.nifi.oper/v1
kind: NifiRegistry
metadata:
  name: nifiregistry-sample
spec:
  # Size - количество реплик
  size: 1
  
  # Используем структуру ImageSpec
  image:
    repository: apache/nifi-registry
    tag: 1.24.0

  # Resources
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "512Mi"

  # Tls (ОТКЛЮЧЕНО)
  tls:
    enabled: true
    port: 8443
    host: nifiregistry-sample-svc.default.svc.cluster.local
    keystorePassword: changeit
    truststorePassword: changeit
    adminIdentity: "root"

  # Настройки Keycloak OIDC
  keycloak:
    discoveryUrl: "https://keycloak:8443/realms/nifi-registry/.well-known/openid-configuration"
    clientId: "nifi-registry-client"
    claimIdentifyingUser: "preferred_username"
    clientSecretName: nifiregistry-keycloak-secret

  # Настройки Flow Storage (ОСТАВЛЕНО)
  flowStorage:
    enabled: true
    size: 200Mi
    storageClass: local-path 

  # Настройки Lib Storage (АКТИВИРОВАНО для ДРАЙВЕРА)
  libStorage:
    enabled: true # <--- АКТИВИРОВАНО для внешней БД
    size: 100Mi
    storageClass: local-path 

  # АКТИВАЦИЯ ВНЕШНЕЙ БАЗЫ ДАННЫХ (PostgreSQL)
  database:
    enabled: true # <--- ИСПРАВЛЕНО: Включаем внешнюю БД
    url: jdbc:postgresql://postgres:5432/nifiregistry 
    driverClass: org.postgresql.Driver
    username: nifiregistry
    password: password # <--- Добавили поле
    