# config/samples/registry_v1_nifiregistry_test.yaml
apiVersion: registry.nifi.oper/v1
kind: NifiRegistry
metadata:
  labels:
    app.kubernetes.io/name: nifiregistry
    app.kubernetes.io/instance: nifiregistry-sample
    app.kubernetes.io/part-of: nreg-oper
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nreg-oper
  name: nifiregistry-sample
spec:
  size: 1
  image:
    repository: apache/nifi-registry
    tag: 1.25.0
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  # Конфигурация базы данных
  database:
    enabled: true
    secretName: postgres-password 
    username: nifiregistry
    url: jdbc:postgresql://nifiregistry-sample-postgres-service:5432/nifiregistry
    driverClass: org.postgresql.Driver
  # Конфигурация PostgreSQL, которая будет развернута оператором
  postgreSQL:
    enabled: true
    image: 
      repository: postgres
      tag: 15-alpine
    size: 200Mi
    database: nifiregistry
    username: nifiregistry
    password: mysecurepassword123
    storageClass: local-path
  # Конфигурация хранилища Flows
  flowStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path
  # Конфигурация хранилища Libraries (Lib) <--- ДОБАВЛЕНО
  libStorage:
    enabled: true
    size: 500Mi
    storageClass: local-path
    